name = "medications"
pages_build_output_dir = "./dist"
compatibility_date = "2025-03-29"
r2_buckets = [
    { binding = "BUCKET", bucket_name = "assets", preview_bucket_name = "assets" },
    { binding = "ANALYTICS_BUCKET", bucket_name = "analytics-logs", preview_bucket_name = "analytics-logs" }
]
